name: URL Checker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "BROWSR-MTHRFCKR.md, CRACKED-WINDOWS-APPSGAMES.md, DEV-MTHRFCKR.md, DIRECT-DOWNLOAD-LINK-(DDL).md, DOWNLOADERS.md, DOXING.md
ILLEGAL-SERVICES.md, INTERNET-PROTOCOL-TELEVISION-(IPTV).md, MEDIA-MTHRFCKR.md, MODDED-ANDROID-APPSGAMES.md, MORE-FEATURES.md
MTHRFCKR.md, PIRACY-MTHRFCKR.md, PORTABLE-APPS.md, PRODUCTIVITY-MTHRFCKR.md, RAINDRPS-MTHRFCKR.md, README.md, REFERENCE-MTHRFCKR.md, 
SEARCH PARTY MTHRFCKR!.md, SOCIAL-MTHRFCKR.md, STREAMING.md, TECH-MTHRFCKR.md, TOOLS-MTHRFCKR.md, TORRENTING.md, USEFUL-WEBSITES.md"


